# Generated by Django 2.2.4 on 2019-09-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='enrolled_course',
        ),
    ]
