# Generated by Django 2.2.4 on 2019-09-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_course',
            field=models.CharField(default='CSIT', max_length=100),
        ),
    ]
