# Generated by Django 2.2.4 on 2019-10-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_announcement_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
