# Generated by Django 2.2.4 on 2019-10-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20191021_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='start_date',
        ),
    ]
